package com.java.practice.javaExceptions;

public class ThrowNewException {
        public static void main(String[] args) {
            System.out.println("ending..");
throw new RuntimeException("test");
        }
}
